# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CadastrarPessoa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar_Pessoa(object):
    def setupUi(self, Cadastrar_Pessoa):
        Cadastrar_Pessoa.setObjectName("Cadastrar_Pessoa")
        Cadastrar_Pessoa.resize(640, 480)
        Cadastrar_Pessoa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NOME_CA = QtWidgets.QLineEdit(Cadastrar_Pessoa)
        self.NOME_CA.setGeometry(QtCore.QRect(120, 110, 341, 21))
        self.NOME_CA.setStyleSheet("")
        self.NOME_CA.setObjectName("NOME_CA")
        self.NOME_CA_2 = QtWidgets.QLineEdit(Cadastrar_Pessoa)
        self.NOME_CA_2.setGeometry(QtCore.QRect(120, 150, 341, 21))
        self.NOME_CA_2.setStyleSheet("")
        self.NOME_CA_2.setObjectName("NOME_CA_2")
        self.NOME_CA_3 = QtWidgets.QLineEdit(Cadastrar_Pessoa)
        self.NOME_CA_3.setGeometry(QtCore.QRect(120, 190, 341, 21))
        self.NOME_CA_3.setStyleSheet("")
        self.NOME_CA_3.setObjectName("NOME_CA_3")
        self.pushButton = QtWidgets.QPushButton(Cadastrar_Pessoa)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 221, 28))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Cadastrar_Pessoa)
        self.label.setGeometry(QtCore.QRect(20, 110, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Cadastrar_Pessoa)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Cadastrar_Pessoa)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Cadastrar_Pessoa)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 631, 51))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Cadastrar_Pessoa)
        QtCore.QMetaObject.connectSlotsByName(Cadastrar_Pessoa)

    def retranslateUi(self, Cadastrar_Pessoa):
        _translate = QtCore.QCoreApplication.translate
        Cadastrar_Pessoa.setWindowTitle(_translate("Cadastrar_Pessoa", "Dialog"))
        self.NOME_CA.setText(_translate("Cadastrar_Pessoa", "Alice"))
        self.NOME_CA_2.setText(_translate("Cadastrar_Pessoa", "Barros Melo"))
        self.NOME_CA_3.setText(_translate("Cadastrar_Pessoa", "81844874524"))
        self.pushButton.setText(_translate("Cadastrar_Pessoa", "CADASTRAR PESSOA"))
        self.label.setText(_translate("Cadastrar_Pessoa", "NOME:"))
        self.label_2.setText(_translate("Cadastrar_Pessoa", "SOBRENOME:"))
        self.label_3.setText(_translate("Cadastrar_Pessoa", "CPF:"))
        self.label_5.setText(_translate("Cadastrar_Pessoa", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#00aaff;\">CADASTRAR PESSOA</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastrar_Pessoa = QtWidgets.QDialog()
    ui = Ui_Cadastrar_Pessoa()
    ui.setupUi(Cadastrar_Pessoa)
    Cadastrar_Pessoa.show()
    sys.exit(app.exec_())
