# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro_conta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_cadastrar_conta(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.button_cadastrar.setGeometry(QtCore.QRect(300, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_cadastrar.setFont(font)
        self.button_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_cadastrar.setObjectName("button_cadastrar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 160, 281, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 185, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.button_voltar.setGeometry(QtCore.QRect(300, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_voltar.setFont(font)
        self.button_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_voltar.setObjectName("button_voltar")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(190, 40, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 160, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 185, 281, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 210, 281, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.button_selecionar = QtWidgets.QPushButton(self.centralwidget)
        self.button_selecionar.setGeometry(QtCore.QRect(490, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_selecionar.setFont(font)
        self.button_selecionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_selecionar.setObjectName("button_selecionar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_2.setText(_translate("MainWindow", "Limite:"))
        self.label_3.setText(_translate("MainWindow", "Numero da Conta:"))
        self.button_voltar.setText(_translate("MainWindow", "Voltar"))
        self.titulo.setText(_translate("MainWindow", "CADASTRAR CONTA"))
        self.label.setText(_translate("MainWindow", "CPF do cliente:"))
        self.button_selecionar.setText(_translate("MainWindow", "Selecionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_cadastrar_conta()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
