# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CriarConta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 631, 51))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.NOME_CA = QtWidgets.QLineEdit(Dialog)
        self.NOME_CA.setGeometry(QtCore.QRect(150, 110, 341, 21))
        self.NOME_CA.setStyleSheet("")
        self.NOME_CA.setText("")
        self.NOME_CA.setObjectName("NOME_CA")
        self.NOME_CA_2 = QtWidgets.QLineEdit(Dialog)
        self.NOME_CA_2.setGeometry(QtCore.QRect(150, 150, 341, 21))
        self.NOME_CA_2.setStyleSheet("")
        self.NOME_CA_2.setText("")
        self.NOME_CA_2.setObjectName("NOME_CA_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 58, 16))
        self.label.setObjectName("label")
        self.NOME_CA_3 = QtWidgets.QLineEdit(Dialog)
        self.NOME_CA_3.setGeometry(QtCore.QRect(150, 190, 341, 21))
        self.NOME_CA_3.setStyleSheet("")
        self.NOME_CA_3.setText("")
        self.NOME_CA_3.setObjectName("NOME_CA_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 250, 221, 28))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#00aaff;\">CRIAR CONTA</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "LIMITE:"))
        self.label_3.setText(_translate("Dialog", "CPF DO CLIENTE:"))
        self.label.setText(_translate("Dialog", "NÚMERO:"))
        self.pushButton.setText(_translate("Dialog", "CRIAR CONTA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
