# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_saque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_saque(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(270, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.button_sacar = QtWidgets.QPushButton(self.centralwidget)
        self.button_sacar.setGeometry(QtCore.QRect(270, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_sacar.setFont(font)
        self.button_sacar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_sacar.setObjectName("button_sacar")
        self.button_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.button_voltar.setGeometry(QtCore.QRect(270, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_voltar.setFont(font)
        self.button_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_voltar.setObjectName("button_voltar")
        '''self.button_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar.setGeometry(QtCore.QRect(490, 135, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_buscar.setFont(font)
        self.button_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_buscar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.button_buscar.setObjectName("button_buscar")'''
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 165, 281, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        '''self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 135, 281, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 140, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")'''
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "SAQUE"))
        self.button_sacar.setText(_translate("MainWindow", "Sacar"))
        self.button_voltar.setText(_translate("MainWindow", "Voltar"))
        #self.button_buscar.setText(_translate("MainWindow", "Buscar"))
        self.label_2.setText(_translate("MainWindow", "VALOR:"))
        #self.label.setText(_translate("MainWindow", "CPF DA CONTA:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
